#! /bin/bash
gcc -o evm evm.c -ggdb
gcc -o asm asm.c
#gcc -o ast ast.c
#touch resultat_e1.txt
#touch resultat_e2.txt
#touch erreur.txt
#clear
#echo Execution de la VM sur la 1er fichier
#./evm e1.bin > resultat_e1.txt 2> erreur.txt
#echo Execution de la VM sur le 2eme fichier
#./evm e2.bin > resultat_e2.txt 2> erreur.txt < infile.bin
#echo Merci Lounes
#gedit resultat_e1.txt resultat_e2.txt erreur.txt &
